-- MySQL Script generated by MySQL Workbench
-- Wed Jun 12 00:14:19 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `default_schema` ;

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `default_schema` ;
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `default_schema` ;

-- -----------------------------------------------------
-- Table `mydb`.`Proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedores` (
  `ID_Proveedores` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Proveedor` VARCHAR(30) NOT NULL,
  `Direccion_Proveedor` VARCHAR(45) NOT NULL,
  `Correo_Electrónico` VARCHAR(45) NOT NULL,
  `Telefono` INT NOT NULL,
  PRIMARY KEY (`ID_Proveedores`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `default_schema`.`Compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_schema`.`Compras` (
  `ID_Compras` INT NOT NULL AUTO_INCREMENT,
  `FK_Proveedores` INT NOT NULL,
  `Precio_Total` DECIMAL(10,0) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  PRIMARY KEY (`ID_Compras`),
  INDEX `FK_Proveedores_idx` (`FK_Proveedores` ASC) VISIBLE,
  CONSTRAINT `FK_Proveedores`
    FOREIGN KEY (`FK_Proveedores`)
    REFERENCES `mydb`.`Proveedores` (`ID_Proveedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Productos` (
  `ID_Productos` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Producto` VARCHAR(45) NOT NULL,
  `Precio_Venta` DECIMAL(10,0) NOT NULL,
  `Precio_Compra` DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (`ID_Productos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `default_schema`.`Detalle_Compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_schema`.`Detalle_Compras` (
  `ID_Detalle_Compras` INT NOT NULL AUTO_INCREMENT,
  `FK_Compras` INT NOT NULL,
  `FK_Productos` INT NOT NULL,
  `Precio_Unitario` DECIMAL(10,0) NOT NULL,
  `Cantidad` INT NOT NULL,
  PRIMARY KEY (`ID_Detalle_Compras`),
  INDEX `FK_Compras_idx` (`FK_Compras` ASC) VISIBLE,
  INDEX `FK_Productos_idx` (`FK_Productos` ASC) VISIBLE,
  CONSTRAINT `FK_Compras`
    FOREIGN KEY (`FK_Compras`)
    REFERENCES `default_schema`.`Compras` (`ID_Compras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Productos`
    FOREIGN KEY (`FK_Productos`)
    REFERENCES `mydb`.`Productos` (`ID_Productos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `ID_Clientes` INT NOT NULL AUTO_INCREMENT,
  `DNI` INT NOT NULL,
  `Apellido_Nombre` VARCHAR(50) NOT NULL,
  `Mail` VARCHAR(55) NOT NULL,
  `Telefono` VARCHAR(30) NOT NULL,
  `Direccion` VARCHAR(60) NULL,
  `Es_Jubilado` TINYINT NOT NULL,
  PRIMARY KEY (`ID_Clientes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ventas` (
  `ID_Ventas` INT NOT NULL AUTO_INCREMENT,
  `FK_Clientes` INT NULL,
  `Precio_Total` DECIMAL(10,0) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  PRIMARY KEY (`ID_Ventas`),
  INDEX `FK_Clientes_idx` (`FK_Clientes` ASC) VISIBLE,
  CONSTRAINT `FK_Clientes`
    FOREIGN KEY (`FK_Clientes`)
    REFERENCES `mydb`.`Clientes` (`ID_Clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Detalle_Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Detalle_Ventas` (
  `ID_Detalle_Ventas` INT NOT NULL AUTO_INCREMENT,
  `FK_Ventas` INT NOT NULL,
  `FK_Productos` INT NOT NULL,
  `Precio_Unitario` DECIMAL(10) NOT NULL,
  `Cantidad` INT NOT NULL,
  PRIMARY KEY (`ID_Detalle_Ventas`),
  INDEX `idProducto_idx` (`FK_Productos` ASC) VISIBLE,
  INDEX `idVenta_idx` (`FK_Ventas` ASC) VISIBLE,
  CONSTRAINT `ID_Productos`
    FOREIGN KEY (`FK_Productos`)
    REFERENCES `mydb`.`Productos` (`ID_Productos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_Ventas`
    FOREIGN KEY (`FK_Ventas`)
    REFERENCES `mydb`.`Ventas` (`ID_Ventas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

